// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiLibraryManagement.Repositories;

namespace WebApiLibraryManagement.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20210429082627_CreateInitial")]
    partial class CreateInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiLibraryManagement.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(3179),
                            FirstName = "Marjane",
                            Gender = "Female",
                            LastName = "Satrapi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4226),
                            FirstName = "Frederick",
                            Gender = "Male",
                            LastName = "Douglass"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4232),
                            FirstName = "Barbara",
                            Gender = "Female",
                            LastName = "Barron"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4234),
                            FirstName = "Masashi",
                            Gender = "Male",
                            LastName = "Kishimoto"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4236),
                            FirstName = "Martin",
                            Gender = "Male",
                            LastName = "Evening"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4238),
                            FirstName = "Amadea",
                            Gender = "Female",
                            LastName = "Morningstar"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4239),
                            FirstName = "Elizabeth",
                            Gender = "Female",
                            LastName = "Zimmermann"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4241),
                            FirstName = "Al",
                            Gender = "Male",
                            LastName = "Seckel"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4242),
                            FirstName = "Ann",
                            Gender = "Female",
                            LastName = "Lawson Christine"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4244),
                            FirstName = "Deibler ",
                            Gender = "Female",
                            LastName = "Rose Darlene"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 567, DateTimeKind.Local).AddTicks(6624),
                            Image = "https://img.thriftbooks.com/api/images/m/2540127da455500c49d0c50c71683b6f38f0b70b.jpg",
                            Status = "Exist",
                            Title = "Persepolis : The Story of a Childhood"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 568, DateTimeKind.Local).AddTicks(8080),
                            Image = "https://img.thriftbooks.com/api/images/m/8303521a462dc3511f365b692830e3e16b370742.jpg",
                            Status = "Borowed",
                            Title = "Narrative of the Life of Frederick Douglass, an American Slave"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 568, DateTimeKind.Local).AddTicks(8100),
                            Image = "https://img.thriftbooks.com/api/images/m/721d5caa481de1e0b2ac04205606f92cce1adeae.jpg",
                            Status = "Exist",
                            Title = "Do What You Are : Discover the Perfect Career for You Through the Secrets of Personality Type"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 568, DateTimeKind.Local).AddTicks(8103),
                            Image = "https://img.thriftbooks.com/api/images/m/456fbecc05164ed1e327ff5ee9922475d1e38df0.jpg",
                            Status = "Exist",
                            Title = "Naruto, Vol. 3"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 568, DateTimeKind.Local).AddTicks(8104),
                            Image = "https://img.thriftbooks.com/api/images/m/f1690297c45711d15406be34e5397b6fcf843718.jpg",
                            Status = "Exist",
                            Title = "Adobe Photoshop CS3 for Photographers : A Professional Image Editor's Guide to the Creative Use of Photoshop for the Macintosh and PC"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 568, DateTimeKind.Local).AddTicks(8106),
                            Image = "https://img.thriftbooks.com/api/images/m/5ac192845cdf424b29b55fbfa03e0db7e0d278ff.jpg",
                            Status = "Exist",
                            Title = "The Ayurvedic Cookbook"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 568, DateTimeKind.Local).AddTicks(8108),
                            Image = "https://img.thriftbooks.com/api/images/m/d7b2a08125cda604e3ba179b5f2fa64f56ee8583.jpg",
                            Status = "Exist",
                            Title = "Elizabeth Zimmermann's Knitter's Almanac"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 568, DateTimeKind.Local).AddTicks(8109),
                            Image = "https://m.media-amazon.com/images/I/51788Fh430L._SL350_.jpg",
                            Status = "Exist",
                            Title = "The Ultimate Book of Optical Illusions"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 568, DateTimeKind.Local).AddTicks(8115),
                            Image = "https://img.thriftbooks.com/api/images/m/8007fc770cbec3c2baaa3026595550d44fc907d4.jpg",
                            Status = "Exist",
                            Title = "Understanding the Borderline Mother : Helping Her Children Transcend the Intense, Unpredictable, and Volatile Relationship"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 10,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 568, DateTimeKind.Local).AddTicks(8116),
                            Image = "https://m.media-amazon.com/images/I/415K3VeI3zL._SL350_.jpg",
                            Status = "Exist",
                            Title = "Evidence Not Seen: A Woman's Miraculous Faith in the Jungles of World War II"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5536),
                            Status = "Approved",
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(6223),
                            Status = "Approved",
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(6229),
                            Status = "Waiting",
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(6231),
                            Status = "Rejected",
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(6232),
                            Status = "Approved",
                            UserId = 8
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowRequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BorrowRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BorrowRequestId");

                    b.ToTable("BorrowRequestDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowRequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            BorrowRequestId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            BorrowRequestId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            BorrowRequestId = 2
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            BorrowRequestId = 3
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            BorrowRequestId = 3
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(4539),
                            Name = "Arts & Music"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5300),
                            Name = "Biographies"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5305),
                            Name = "Business"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5307),
                            Name = "Comics"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5309),
                            Name = "Computers & Tech"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5310),
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5312),
                            Name = "Education & Reference"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5313),
                            Name = "Logic & Brain Teaser Books"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5315),
                            Name = "Health & Fitness"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(5316),
                            Name = "History Books "
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleDescription = "Admin can do the following actions: Viewing/Adding/Updating/Deleting a Category; Viewing/Adding/Updating/Deleting a Book; Viewing the list of borrowing requests; Approving/Rejecting request from Normal User",
                            UserRoles = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleDescription = "User can do the following actions: Borrowing book. One borrowing request can request more than 1 book (maximum is 5 books and 3 borrowing requests in a month); Normal User can see the list of books that he/she already borrowed with status (Approve/Reject/Waiting)",
                            UserRoles = "User"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ha Noi",
                            Age = 24,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(7924),
                            DateOfBirth = new DateTime(1997, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            Gender = "Male",
                            LastName = "A",
                            Password = "123456",
                            Phone = "0123456789",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ha Noi",
                            Age = 24,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(9240),
                            DateOfBirth = new DateTime(1997, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@gmail.com",
                            FirstName = "User",
                            Gender = "Male",
                            LastName = "A",
                            Password = "123456",
                            Phone = "0123456789",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ha Noi",
                            Age = 24,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(9245),
                            DateOfBirth = new DateTime(1997, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh@gmail.com",
                            FirstName = "Manh",
                            Gender = "Male",
                            LastName = "Nguyen",
                            Password = "123456",
                            Phone = "0123456789",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Quang Ninh",
                            Age = 23,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(9359),
                            DateOfBirth = new DateTime(1998, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tung@gmail.com",
                            FirstName = "Tung",
                            Gender = "Male",
                            LastName = "Tran",
                            Password = "123456",
                            Phone = "0987654321",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ha Noi",
                            Age = 22,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(9362),
                            DateOfBirth = new DateTime(1999, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "trang@gmail.com",
                            FirstName = "Trang",
                            Gender = "Female",
                            LastName = "Bui",
                            Password = "123456",
                            Phone = "0123789456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ho Chi Minh",
                            Age = 21,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(9367),
                            DateOfBirth = new DateTime(2000, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thu@gmail.com",
                            FirstName = "Thu",
                            Gender = "Female",
                            LastName = "Nguyen",
                            Password = "123456",
                            Phone = "0456123789",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "Nghe An",
                            Age = 20,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(9370),
                            DateOfBirth = new DateTime(2001, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hung@gmail.com",
                            FirstName = "Hung",
                            Gender = "Male",
                            LastName = "Nguyen",
                            Password = "123456",
                            Phone = "0789456123",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            Address = "Da Nang",
                            Age = 19,
                            CreatedDate = new DateTime(2021, 4, 29, 15, 26, 26, 570, DateTimeKind.Local).AddTicks(9373),
                            DateOfBirth = new DateTime(2002, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "toan@gmail.com",
                            FirstName = "Toan",
                            Gender = "Male",
                            LastName = "Tran",
                            Password = "123456",
                            Phone = "0789123456",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Book", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiLibraryManagement.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowRequest", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.User", "User")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowRequestDetail", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.Book", "Book")
                        .WithMany("BorrowRequestDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiLibraryManagement.Models.BorrowRequest", "BorrowRequest")
                        .WithMany("BorrowRequestDetails")
                        .HasForeignKey("BorrowRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BorrowRequest");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.User", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Book", b =>
                {
                    b.Navigation("BorrowRequestDetails");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowRequest", b =>
                {
                    b.Navigation("BorrowRequestDetails");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.User", b =>
                {
                    b.Navigation("BorrowRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
