// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiLibraryManagement.Models.FluentAPI.Relationships.Required;

namespace WebApiLibraryManagement.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiLibraryManagement.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 896, DateTimeKind.Local).AddTicks(9768),
                            FirstName = "Manh",
                            Gender = "Male",
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(1437),
                            FirstName = "Linh",
                            Gender = "Female",
                            LastName = "Tran"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(1447),
                            FirstName = "Huong",
                            Gender = "Female",
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(1450),
                            FirstName = "Mai",
                            Gender = "Female",
                            LastName = "Bui"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(1452),
                            FirstName = "Kien",
                            Gender = "Male",
                            LastName = "Do"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(1455),
                            FirstName = "Dung",
                            Gender = "Male",
                            LastName = "Nguyen"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 892, DateTimeKind.Local).AddTicks(3181),
                            Title = "JavaScript"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 894, DateTimeKind.Local).AddTicks(4965),
                            Title = "C#"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 894, DateTimeKind.Local).AddTicks(5041),
                            Title = "HTML"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 894, DateTimeKind.Local).AddTicks(5047),
                            Title = "CSS"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 894, DateTimeKind.Local).AddTicks(5052),
                            Title = "React"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 894, DateTimeKind.Local).AddTicks(5057),
                            Title = "Unit Test"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 894, DateTimeKind.Local).AddTicks(5061),
                            Title = "Note Js"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowingRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(3686),
                            Status = "Approving",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(5143),
                            Status = "Approving",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(5196),
                            Status = "Pending",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(5198),
                            Status = "Rejecting",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(5200),
                            Status = "Approving",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BorrowingRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BorrowingRequestId");

                    b.ToTable("BorrowingRequestDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowingRequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            BorrowingRequestId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            BorrowingRequestId = 1
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            BorrowingRequestId = 1
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            BorrowingRequestId = 2
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            BorrowingRequestId = 3
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(1942),
                            Name = "Front End"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(3096),
                            Name = "Back End"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleDescription = "Admin can do the following actions: Viewing/Adding/Updating/Deleting a Category; Viewing/Adding/Updating/Deleting a Book; Viewing the list of borrowing requests; Approving/Rejecting request from Normal User",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleDescription = "User can do the following actions: Borrowing book. One borrowing request can request more than 1 book (maximum is 5 books and 3 borrowing requests in a month); Normal User can see the list of books that he/she already borrowed with status (Approve/Reject/Waiting)",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 897, DateTimeKind.Local).AddTicks(8017),
                            Email = "manh@gmail.com",
                            FirstName = "Manh",
                            Gender = "Male",
                            LastName = "Nguyen",
                            Password = "123456",
                            Phone = "0123456789",
                            RoleId = 1,
                            UserName = "Manh"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 898, DateTimeKind.Local).AddTicks(77),
                            Email = "tung@gmail.com",
                            FirstName = "Tung",
                            Gender = "Male",
                            LastName = "Tran",
                            Password = "123456",
                            Phone = "9876543210",
                            RoleId = 2,
                            UserName = "Tung"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 898, DateTimeKind.Local).AddTicks(89),
                            Email = "trang@gmail.com",
                            FirstName = "Trang",
                            Gender = "Female",
                            LastName = "Bui",
                            Password = "123456",
                            Phone = "1237894560",
                            RoleId = 2,
                            UserName = "Trang"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 898, DateTimeKind.Local).AddTicks(95),
                            Email = "thu@gmail.com",
                            FirstName = "Thu",
                            Gender = "Female",
                            LastName = "Nguyen",
                            Password = "123456",
                            Phone = "4561237890",
                            RoleId = 2,
                            UserName = "Thu"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 898, DateTimeKind.Local).AddTicks(97),
                            Email = "hung@gmail.com",
                            FirstName = "Hung",
                            Gender = "Male",
                            LastName = "Nguyen",
                            Password = "123456",
                            Phone = "7894561230",
                            RoleId = 2,
                            UserName = "Hung"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 4, 15, 0, 23, 28, 898, DateTimeKind.Local).AddTicks(100),
                            Email = "toan@gmail.com",
                            FirstName = "Toan",
                            Gender = "Male",
                            LastName = "Tran",
                            Password = "123456",
                            Phone = "7891234560",
                            RoleId = 2,
                            UserName = "Toan"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Book", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiLibraryManagement.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequest", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.User", "User")
                        .WithMany("BorrowingRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequestDetail", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.Book", "Book")
                        .WithMany("BorrowingRequestDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiLibraryManagement.Models.BorrowingRequest", "BorrowingRequest")
                        .WithMany("BorrowingRequestDetails")
                        .HasForeignKey("BorrowingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BorrowingRequest");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.User", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Book", b =>
                {
                    b.Navigation("BorrowingRequestDetails");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequest", b =>
                {
                    b.Navigation("BorrowingRequestDetails");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.User", b =>
                {
                    b.Navigation("BorrowingRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
