// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiLibraryManagement.Repositories;

namespace WebApiLibraryManagement.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiLibraryManagement.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(236),
                            FirstName = "Manh",
                            Gender = "Male",
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(3097),
                            FirstName = "Linh",
                            Gender = "Female",
                            LastName = "Tran"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(3116),
                            FirstName = "Huong",
                            Gender = "Female",
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(3120),
                            FirstName = "Mai",
                            Gender = "Female",
                            LastName = "Bui"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(3125),
                            FirstName = "Kien",
                            Gender = "Male",
                            LastName = "Do"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(3130),
                            FirstName = "Dung",
                            Gender = "Male",
                            LastName = "Nguyen"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 478, DateTimeKind.Local).AddTicks(6879),
                            Title = "JavaScript"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 480, DateTimeKind.Local).AddTicks(297),
                            Title = "C#"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 480, DateTimeKind.Local).AddTicks(336),
                            Title = "HTML"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 480, DateTimeKind.Local).AddTicks(340),
                            Title = "CSS"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 480, DateTimeKind.Local).AddTicks(344),
                            Title = "React"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 480, DateTimeKind.Local).AddTicks(346),
                            Title = "Unit Test"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 480, DateTimeKind.Local).AddTicks(429),
                            Title = "Note Js"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowingRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(5541),
                            Status = "Approved",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(6673),
                            Status = "Approved",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(6687),
                            Status = "Waiting",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(6690),
                            Status = "Rejected",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(6692),
                            Status = "Approved",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BorrowingRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BorrowingRequestId");

                    b.ToTable("BorrowingRequestDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowingRequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            BorrowingRequestId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            BorrowingRequestId = 1
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            BorrowingRequestId = 1
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            BorrowingRequestId = 2
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            BorrowingRequestId = 3
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(3682),
                            Name = "Front End"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(5156),
                            Name = "Back End"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleDescription = "Admin can do the following actions: Viewing/Adding/Updating/Deleting a Category; Viewing/Adding/Updating/Deleting a Book; Viewing the list of borrowing requests; Approving/Rejecting request from Normal User",
                            UserRoles = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleDescription = "User can do the following actions: Borrowing book. One borrowing request can request more than 1 book (maximum is 5 books and 3 borrowing requests in a month); Normal User can see the list of books that he/she already borrowed with status (Approve/Reject/Waiting)",
                            UserRoles = "User"
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ha Noi",
                            Age = 24,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 483, DateTimeKind.Local).AddTicks(9785),
                            DateOfBirth = new DateTime(1997, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh@gmail.com",
                            FirstName = "Manh",
                            Gender = "Male",
                            LastName = "Nguyen",
                            Password = "123456",
                            Phone = "0123456789",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Quang Ninh",
                            Age = 23,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 484, DateTimeKind.Local).AddTicks(2644),
                            DateOfBirth = new DateTime(1998, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tung@gmail.com",
                            FirstName = "Tung",
                            Gender = "Male",
                            LastName = "Tran",
                            Password = "123456",
                            Phone = "0987654321",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ha Noi",
                            Age = 22,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 484, DateTimeKind.Local).AddTicks(2655),
                            DateOfBirth = new DateTime(1999, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "trang@gmail.com",
                            FirstName = "Trang",
                            Gender = "Female",
                            LastName = "Bui",
                            Password = "123456",
                            Phone = "0123789456",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ho Chi Minh",
                            Age = 21,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 484, DateTimeKind.Local).AddTicks(2664),
                            DateOfBirth = new DateTime(2000, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thu@gmail.com",
                            FirstName = "Thu",
                            Gender = "Female",
                            LastName = "Nguyen",
                            Password = "123456",
                            Phone = "0456123789",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Address = "Nghe An",
                            Age = 20,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 484, DateTimeKind.Local).AddTicks(2673),
                            DateOfBirth = new DateTime(2001, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hung@gmail.com",
                            FirstName = "Hung",
                            Gender = "Male",
                            LastName = "Nguyen",
                            Password = "123456",
                            Phone = "0789456123",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "Da Nang",
                            Age = 19,
                            CreatedDate = new DateTime(2021, 4, 20, 15, 13, 40, 484, DateTimeKind.Local).AddTicks(2682),
                            DateOfBirth = new DateTime(2002, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "toan@gmail.com",
                            FirstName = "Toan",
                            Gender = "Male",
                            LastName = "Tran",
                            Password = "123456",
                            Phone = "0789123456",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Book", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiLibraryManagement.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequest", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.User", "User")
                        .WithMany("BorrowingRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequestDetail", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.Book", "Book")
                        .WithMany("BorrowingRequestDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiLibraryManagement.Models.BorrowingRequest", "BorrowingRequest")
                        .WithMany("BorrowingRequestDetails")
                        .HasForeignKey("BorrowingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BorrowingRequest");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.User", b =>
                {
                    b.HasOne("WebApiLibraryManagement.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Book", b =>
                {
                    b.Navigation("BorrowingRequestDetails");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.BorrowingRequest", b =>
                {
                    b.Navigation("BorrowingRequestDetails");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApiLibraryManagement.Models.User", b =>
                {
                    b.Navigation("BorrowingRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
